spring.application.name=brahmavanam

spring.jpa.hibernate.ddl-auto=update

master.authenticationKey=123456
master.password=rksdsvas

server.servlet.session.persistent=false

# Disable schema.sql — tables managed by JPA ddl-auto
spring.sql.init.mode=never
